@startuml MonsterTradingCards
class Server

class ConnectionHandler

' Command/Routing still missing

class Logger

class Repository

class PostGresDatabase

enum BattleState {
    WAITING
    IN_PROGRESS
    DONE
    NONE
}

' How will a battle be done

class Battle

class BattleLogic {
    -Player p1
    -Player p2
    -BattleState state


}
' is Player really necessary?
class Player {
    -int playerId
    -string username
    -int elo
    -CardStack stack
    -CardDeck deck

    +int getPlayerId()
    +void setPlayerId(int playerId)
    +string getUsername()
    +void setUsername(string username)
    +int getElo()
    +void setElo(int elo)
}

class CardStack {
    -list<Card> allCards

    +list<Card> getAllCards()
    +Card getCardByIndex(int cardIdx)
    +Card getCardById(int cardId)
    +void addCardToStack(Card card)
}

class CardDeck {
    -list<Card> cards

    +Card getCardByIndex(int cardIdx)
    +Card getCardById(int cardId)
    +void addCard(Card card)
    +int getAmountCards()
}

abstract class Card {
    #int cardId
    #int playerId
    #string cardName
    #double damage
    #ElementType elementType

    +ElementType getElementType()
    +void setElementType(ElementType elementType)
    +double getDamage()
    +void setDamage(double damage)
    +int getPlayerId()
    +void setPlayerId(int playerId)
    +int getCardId()
    +void setCardId(int cardId)
}

enum ElementType {
    WATER
    FIRE
    NORMAL
}

enum MonsterType {
    GOBLIN
    DRAGON
    WIZARD
    ORK
    KNIGHT
    KRAKEN
    ELVE
    TROLL
}

class MonsterCard {
    -MonsterType MonsterType


    +MonsterType getMonsterType()
    +void setMonsterType(MonsterType monsterType)
}

class SpellCard {

}

Card - ElementType
MonsterCard - MonsterType

MonsterCard --|> Card
SpellCard --|> Card

@enduml